### PR TITLE
[FIX] Make project compatible with ROS Noetic

### PR DESCRIPTION
**Pull request by Scout22**
Fix deprecated OpenCV enum to handle opencv 4.0 and ROS Noetic

### CODE REVIEW

**Comment by pjreed** [comment]
Thanks, this looks good to me.  (@danthony06)

**Comment by danthony06** [comment]
Thanks, I'm traveling, but will get this merged on Thursday.

**Comment by danthony06** [comment]
Thanks!

**Comment by danthony06** [comment]
@Scout22 Thanks for the fix. I merged it in and created a Noetic release. I've bloomed the release and you can track the progress here: https://github.com/ros/rosdistro/pull/32108.

**Pull request merged**
